### ISSUE TITLE
Missing jQuery

### ISSUE THREAD

**Issue by robindrost** [pagekit/extension-tinymce#1]
Hello,

I just tried out the plugin but it won't load while creating a page. It seems like the plugin is looking for a jQuery asset inside the plugin assets folder but cannot find it.
![screen shot 2016-04-14 at 14 42 14](https://cloud.githubusercontent.com/assets/588012/14528290/1dc27f1c-024f-11e6-9ed6-4d23ba69b1be.png)

**Comment by malte-christian** [comment]
Did you installed the package from the marketplace? If not did you run `npm install` inside the package folder?

**Comment by kamal-chagam** [comment]
Hi
i could see that jquery file, but still the same error .. any work around

**Comment by robindrost** [comment]
Hi @MalteScharenberg 
Thanks for the reply. I ran npm install but the problem still exist.

**Comment by kamal-chagam** [comment]
what i observed from url shown in error is  
**http://localhost:8000/index.php/packages/pagekit/tinymce/app/assets/tinymce/tinymce.jquery.min.js**

but it should be like this ( as it's working ) , don't know why 
**http://localhost:8000/packages/pagekit/tinymce/app/assets/tinymce/tinymce.jquery.min.js**

inside packages/pagekit/tinymce/app/bundle/tinymce.js or packages/pagekit/tinymce/app/components/editor-tinymce.js: 

I changed this line 
var  baseURL = $pagekit.url + '/packages/pagekit/tinymce/app/assets/tinymce'
to 
var baseURL = 'http://localhost:8000/packages/pagekit/tinymce/app/assets/tinymce',

**Comment by malte-christian** [comment]
@chagamkamalakar you pointed me in the right direction. `$pagekit.url` contains at your system `/index.php` because you both have mod_rewrite disabled. For pagekit routes `/index.php` is then needed, but for static files it is clearly wrong.

**Comment by kamal-chagam** [comment]
thank you @MalteScharenberg

**Comment by malte-christian** [comment]
Update is available via marketplace.
