### ISSUE TITLE
Editor doesn't show up

### ISSUE THREAD

**Issue by benedictdudel** [pagekit/extension-tinymce#3]
Hey Guys,

I tried installing the extension from your marketplace and at first it seems that the installation were successfully. But on e.g. a site page where the editor is called, I get the following error:

```
Uncaught (in promise) ReferenceError: tinyMCE is not defined
    at VueComponent.<anonymous> (http://myurl/packages/pagekit/tinymce/app/bundle/tinymce.js?v=6e9e:1:613)(anonymous function) @ tinymce.js?v=6e9e:1
tinymce.js?v=6e9e:1 Uncaught (in promise) ReferenceError: tinyMCE is not defined(…)(anonymous function) @ tinymce.js?v=6e9e:1
```

**Comment by malte-christian** [comment]
This was caused by a false build. Update is available via marketplace.

**Comment by benedictdudel** [comment]
cool, thanks!!
